// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJdgX77ZN5lKGHTPmKpLbOsH5pWPJMOA',
    appId: '1:907168118851:web:a6ce0184142cda385f3cf6',
    messagingSenderId: '907168118851',
    projectId: 'student-portal-66f8f',
    authDomain: 'student-portal-66f8f.firebaseapp.com',
    storageBucket: 'student-portal-66f8f.appspot.com',
    measurementId: 'G-MR2KZCNEG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Qc2b1rhqu-u6Y4pz0tsGB8fA4jmFuYI',
    appId: '1:907168118851:android:235320ce908990295f3cf6',
    messagingSenderId: '907168118851',
    projectId: 'student-portal-66f8f',
    storageBucket: 'student-portal-66f8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY4MjXcl5_Hs9xhd4pdoPD1uiDhPRiG1M',
    appId: '1:907168118851:ios:8a807ea0bfa372f35f3cf6',
    messagingSenderId: '907168118851',
    projectId: 'student-portal-66f8f',
    storageBucket: 'student-portal-66f8f.appspot.com',
    iosBundleId: 'com.lucasdennis.studentPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY4MjXcl5_Hs9xhd4pdoPD1uiDhPRiG1M',
    appId: '1:907168118851:ios:1ae08a2e4e8aed045f3cf6',
    messagingSenderId: '907168118851',
    projectId: 'student-portal-66f8f',
    storageBucket: 'student-portal-66f8f.appspot.com',
    iosBundleId: 'com.lucasdennis.studentPortal.RunnerTests',
  );
}
